/* Y10U2.3 — 2.1 L3 · Who are the members of your family? People and pets. / Parle-moi de ta famille
   Year 10 · Unité 2 — La famille et les amis — family, friends and relationships
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y10U2.3", [
  ["ma famille pense que", "my family thinks that"],
  ["Il y a", "There are"],
  ["il y avait", "there was;there were;there used to be"],
  ["Après avoir", "After having"],
  ["à l'avenir;dans le futur", "in the future"],
  ["avoir des connaissances", "to have knowledge"],
  ["la couleur;couleur", "colour"],
  ["blanc", "white"],
  ["noir", "black"],
  ["bleu", "blue"],
  ["vert", "green"],
  ["comme", "as;like"],
  ["longtemps", "a long time;long time"],
  ["petit-déjeuner", "breakfast"],
  ["ne...personne", "not anyone;no-one"],
  ["personne", "nobody"],
  ["nous avons", "we have"],
  ["vous avez", "you guys have"],
  ["blond", "blond"],
  ["châtain;brun", "brown"],
  ["clair", "light;bright"],
  ["court", "short"],
  ["grand;grande", "big;tall;large"],
  ["gris", "grey"],
  ["long;longue", "long"],
  ["marron", "brown"],
  ["petit", "small;little"],
  ["roux", "red;ginger"],
  ["les cheveux;cheveux", "hair"],
  ["les lunettes;lunettes", "glasses"],
  ["les yeux", "eyes"],
  ["la mère;mère", "mother;mum"],
  ["le père;un père;père", "father;dad"],
  ["jumeau;jumelle;jumeaux", "twin"],
  ["unique", "unique;only (child)"],
  ["l'animal;les animaux", "animal;animals"],
  ["le beau-père", "step-father;step-dad"],
  ["la belle-mère", "step-mother;step-mum"],
  ["le chat;chat", "cat"],
  ["le cheval;cheval", "horse"],
  ["le chien;chien", "dog"],
  ["le demi-frère", "step-brother;half-brother"],
  ["la demi-sœur", "step-sister;half-sister"],
  ["l'enfant", "child;kid"],
  ["la famille;famille", "family"],
  ["la fille", "girl;daughter"],
  ["le fils", "son"],
  ["le frère", "brother"],
  ["la génération", "generation"],
  ["la grand-mère;grand-mère", "grandmother;grandma"],
  ["le grand-père", "grandfather;grandad"],
  ["les grands-parents;grands-parents", "grandparents;grand-parents;grand parents"],
  ["le lapin", "rabbit"],
  ["l'oncle", "uncle"],
  ["le parent", "parent"],
  ["la personne", "people;person;nobody"],
  ["la sœur", "sister"],
  ["la tante;tante", "aunt;auntie;aunty"],
  ["dans", "in;inside"],
  ["Il y aura", "there will be"],
  ["s'appeler", "to be called"],
  ["avoir", "to have;have"],
  ["avoir ... ans;avoir...ans", "to be ... years old;to be...years old"],
  ["playground;court", "cour"],
  ["she runs;he runs;it runs", "court"]
]);
