/* Y10U3.19 — L19 · Describe an accident. Décris un accident
   Year 10 · Unité 3 — La santé et l'égalité — sport, well-being, food and equality
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y10U3.19", [
  ["Avant de", "Before;before doing something"],
  ["l'après-midi", "afternoon"],
  ["alors", "so;then"],
  ["après", "after;afterwards"],
  ["Je me suis blessé", "I injured myself (m)"],
  ["Je me suis blessée", "I injured myself (f)"],
  ["Tu t'es coupé", "You cut yourself (sm)"],
  ["Tu t'es coupée", "You cut yourself (sf)"],
  ["Tu t'es brûlé", "You burned yourself (sm)"],
  ["Tu t'es brûlée", "You burned yourself (sf)"],
  ["Tu t'es blessé", "You injured yourself (sm)"],
  ["Tu t'es blessée", "You injured yourself (sf)"],
  ["Il s'est coupé", "He cut himself"],
  ["Il s'est brûlé", "He burned himself"],
  ["Il s'est blessé", "He injured himself"],
  ["Elle s'est coupée", "She cut herself"],
  ["Elle s'est brûlée", "She burned herself"],
  ["Elle s'est blessée", "She injured herself"],
  ["Nous nous sommes blessés", "We injured ourselves (pm)"],
  ["Nous nous sommes blessées", "We injured ourselves (pf)"],
  ["Vous vous êtes blessé", "You injured yourself (sm)"],
  ["Vous vous êtes blessée", "You injured yourself (sf)"],
  ["Vous vous êtes blessés", "You injured yourselves (pm)"],
  ["Vous vous êtes blessées", "You injured yourselves (pf)"],
  ["Ils se sont coupés", "They cut themselves (mp)"],
  ["Ils se sont brûlés", "They burned themselves (mp)"],
  ["Ils se sont blessés", "They injured themselves (mp)"],
  ["Elles se sont coupées", "They cut themselves (fp)"],
  ["Elles se sont brûlées", "They burned themselves (fp)"],
  ["Elles se sont blessées", "They injured themselves (fp)"],
  ["la bouche", "the mouth;mouth"],
  ["le bras;bras", "the arm;arm"],
  ["le corps", "the body;body"],
  ["le doigt", "the finger;finger"],
  ["la gorge", "the throat;throat"],
  ["la jambe", "the leg;leg"],
  ["la main", "the hand;hand"],
  ["l'oreille", "the ear"],
  ["la peau", "the skin;skin"],
  ["la tête", "the head"],
  ["le ventre", "the stomach;the belly"],
  ["le visage", "the face;face"],
  ["brûler", "to burn"],
  ["couper", "to cut;to switch off"],
  ["se brûler", "to burn yourself"],
  ["se couper", "to cut yourself"],
  ["l'hôpital", "the hospital;hospital"],
  ["médical;médicale", "medical"],
  ["hier", "yesterday"],
  ["l'accident", "the accident"],
  ["le sang", "the blood;blood"],
  ["le secours", "the help;the aid;the assistance"],
  ["le soin", "the care"],
  ["l'urgence", "the emergency"],
  ["ayant", "having"],
  ["blesser", "to hurt;to injure"],
  ["étant", "being"],
  ["souffrir", "to suffer;be in pain"],
  ["tomber", "to fall;fall;to fall down"],
  ["se blesser", "to hurt yourself;to injure yourself"],
  ["majeur;majeure", "major;main"],
  ["aussi", "also;as well;too"],
  ["aussi...que;aussi que", "as...as;as as"],
  ["also", "aussi"],
  ["as...as", "aussi...que"],
  ["ainsi", "so;thus"],
  ["cependant;pourtant;toutefois", "however"],
  ["couple", "couple"]
]);
