/* Y10U3.14 — L14 · What must one do to stay healthy? Que doit-on faire pour rester en forme ?
   Year 10 · Unité 3 — La santé et l'égalité — sport, well-being, food and equality
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y10U3.14", [
  ["il faut + infinitive", "we have to"],
  ["poser une question", "to ask a question"],
  ["répondre à une question", "to answer a question"],
  ["bien sûr", "of course"],
  ["fastfood", "fast food;fast food restaurant"],
  ["restaurant", "restaurant"],
  ["sain", "healthy"],
  ["seulement", "only"],
  ["de temps en temps", "from time to time"],
  ["en ce moment", "at the moment"],
  ["drogue", "drug"],
  ["énergie", "energy"],
  ["exercice", "exercise"],
  ["fois", "time"],
  ["en forme", "in shape;healthy"],
  ["mouvement", "movement"],
  ["santé;la santé", "health"],
  ["par contre", "however"],
  ["bouger", "to move"],
  ["dormir", "to sleep;sleep"],
  ["éviter", "to avoid;avoid"],
  ["marcher", "to walk;walk"],
  ["mener", "to lead"],
  ["rester", "to stay"],
  ["essentiel;essentielle", "essential"],
  ["évident;évidente", "obvious"],
  ["indispensable", "essential;indispensable"],
  ["nécessaire", "necessary;essential"],
  ["facilement", "easily"],
  ["mieux", "better"],
  ["simplement", "simply"],
  ["donc", "therefore;so"],
  ["l'effort", "effort"],
  ["l'idée", "idea"],
  ["la nécessité", "necessity"],
  ["pour", "in order to;for"],
  ["améliorer", "to improve;improve"],
  ["arrêter", "to stop;to arrest;stop"],
  ["réduire", "to reduce;reduce"],
  ["il vaut mieux", "it is better to"],
  ["se reposer", "to rest"],
  ["mars", "March"],
  ["pourtant", "yet;nonetheless"],
  ["to rest", "se reposer"]
]);
