/* Y10U3.26 — L26 · Higher only : Inclusive society. La société ouverte -- Comment peut-on améliorer la société ?
   Year 10 · Unité 3 — La santé et l'égalité — sport, well-being, food and equality
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y10U3.26", [
  ["impossible", "impossible"],
  ["la tolérance", "tolerance"],
  ["tolérer", "to tolerate;tolerate"],
  ["on ne tolère pas", "it's not tolerated;it's not accepted;we don't tolerated;we do not tolerated"],
  ["état", "condition;state"],
  ["handicapé", "disabled;handicapped"],
  ["pauvre", "poor"],
  ["riche", "rich;wealthy"],
  ["vieille;vieux", "old"],
  ["argent", "money"],
  ["écart", "gap"],
  ["égalité", "equality"],
  ["fauteuil roulant", "wheelchair"],
  ["handicap", "disability"],
  ["majorité", "majority"],
  ["maximum", "maximum"],
  ["million", "million"],
  ["minimum", "minimum"],
  ["minorité", "minority"],
  ["moitié", "half"],
  ["plupart", "most"],
  ["tiers", "third"],
  ["ignorer", "to ignore;not know"],
  ["toucher", "to touch;to affect"],
  ["bisexuel", "bisexual"],
  ["hétéro", "straight"],
  ["lesbien", "lesbian"],
  ["transgenre", "transgender"],
  ["lorsque", "when;while"],
  ["attitude", "attitude"],
  ["différence", "difference"],
  ["discrimination", "discrimination"],
  ["expression", "expression"],
  ["identité", "identity"],
  ["jugement", "judgement"],
  ["racisme", "racism"],
  ["religion", "religion"],
  ["sexe", "gender;sex"],
  ["sexisme", "sexism"],
  ["accepter", "to accept;accept"],
  ["défendre de", "to forbid;to ban"],
  ["autre", "other"],
  ["conscient;consciente", "conscious;aware"],
  ["c'est-à-dire", "in other words"],
  ["certainement", "certainly;surely"],
  ["clairement", "clearly"],
  ["complètement", "completely"],
  ["différemment", "differently"],
  ["particulièrement", "particularly"],
  ["l'aspect", "aspect"],
  ["le choc", "shock;clash"],
  ["la condition", "condition"],
  ["la définition", "definition"],
  ["l'espoir", "hope"],
  ["l'exemple", "example"],
  ["la faveur", "favour"],
  ["l'inquiétude", "worry;anxiety"],
  ["la manière", "way;manner"],
  ["la situation", "situation"],
  ["le sujet", "subject;topic"],
  ["le thème", "theme"],
  ["le tort", "wrong;incorrect"],
  ["la valeur", "value;worth"],
  ["la vérité", "truth"],
  ["agir", "to act;act"],
  ["changer;se changer", "to change;to get changed"],
  ["imposer", "to impose;impose"],
  ["juger", "to judge;judge"],
  ["libérer", "to free;to set free;to release"],
  ["vouloir dire", "to mean;to want to say"]
]);
