/* Y10U2.5 — 2.1 L5 · Describe your bedroom. / Décris ta chambre.
   Year 10 · Unité 2 — La famille et les amis — family, friends and relationships
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y10U2.5", [
  ["si j'avais le choix je voudrais", "if I had the choice I would like"],
  ["j'adore", "I love;l love"],
  ["je déteste", "I hate"],
  ["préférer", "to prefer;prefer"],
  ["blanc", "white"],
  ["noir", "black"],
  ["bleu", "blue"],
  ["vert", "green"],
  ["confortable", "comfortable;comfy"],
  ["moderne", "modern"],
  ["aimer", "to like;like"],
  ["jouer", "to play;play"],
  ["partager", "to share;share"],
  ["la table", "table"],
  ["petit-déjeuner", "breakfast"],
  ["l'appartement", "apartment;flat"],
  ["la chambre;chambre", "bedroom;room"],
  ["la maison;une maison", "house;home"],
  ["habiter", "to live;live"],
  ["grand;grande", "big;tall;large"],
  ["gris", "grey"],
  ["marron", "brown"],
  ["petit", "small;little"],
  ["la grand-mère;grand-mère", "grandmother;grandma"],
  ["le grand-père", "grandfather;grandad"],
  ["les grands-parents;grands-parents", "grandparents;grand-parents;grand parents"],
  ["dans", "in;inside"],
  ["sombre", "dark"],
  ["la fenêtre", "window"],
  ["le coin", "corner"],
  ["la lumière", "light"],
  ["la porte", "door"],
  ["habituel", "usual"],
  ["d'habitude", "usually;normally"],
  ["to play", "jouer"],
  ["comfortable", "confortable"],
  ["modern", "moderne"],
  ["dark", "sombre"],
  ["window", "fenêtre (f)"],
  ["corner", "coin (m)"],
  ["light", "lumière (f)"],
  ["door", "porte (f)"],
  ["table", "table (f)"],
  ["to share", "partager"],
  ["usual", "habituel"],
  ["usually", "d'habitude"]
]);
