/* Y10U2.1 — 2.1 L1 · Introduce yourself – name, age and date of birth. / Parle-moi de toi.
   Year 10 · Unité 2 — La famille et les amis — family, friends and relationships
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y10U2.1", [
  ["Après avoir", "After having"],
  ["avoir des connaissances", "to have knowledge"],
  ["il est deux heures", "it is two o'clock;it's two o'clock;it is 2 o'clock;it is 2:00"],
  ["il est trois heures", "it is three o'clock"],
  ["il est quatre heures", "it is four o'clock;it is 4 o'clock"],
  ["il est cinq heures", "it is five o'clock"],
  ["il est sept heures", "it is seven o'clock;it is 7 o'clock"],
  ["il est huit heures", "it is eight o'clock;it is 8 o'clock"],
  ["il est neuf heures", "it is nine o'clock"],
  ["il est onze heures", "it is eleven o'clock"],
  ["il est douze heures", "it is twelve o'clock"],
  ["à huit heures", "at eight o'clock;at 8 o'clock;at 8:00"],
  ["le commentaire", "comment;remark"],
  ["avoir mal", "to ache;to hurt"],
  ["comment ça va?;ça va?", "how are you?"],
  ["le quatrième;la quatrième", "fourth"],
  ["comment", "how"],
  ["anniversaire", "birthday"],
  ["août", "August"],
  ["avril", "April"],
  ["la date", "the date;date"],
  ["décembre", "December"],
  ["février", "February"],
  ["janvier", "January"],
  ["juillet", "July"],
  ["juin", "June"],
  ["mars", "March"],
  ["mois", "month"],
  ["naissance", "birth"],
  ["novembre", "November"],
  ["octobre", "October"],
  ["septembre", "September"],
  ["cinq", "five;5"],
  ["deux", "two"],
  ["dix-huit", "eighteen;18"],
  ["dix-neuf", "nineteen;19"],
  ["dix-sept", "seventeen;17"],
  ["douze", "twelve;12"],
  ["huit", "eight;8"],
  ["mille", "a thousand"],
  ["onze", "eleven;11"],
  ["quatorze", "fourteen;14"],
  ["quatre", "four;4"],
  ["quinze", "fifteen;15"],
  ["seize", "sixteen;16"],
  ["sept", "seven;7"],
  ["treize", "thirteen;13"],
  ["trente", "thirty;30"],
  ["trois", "three;3"],
  ["vingt", "twenty;20"],
  ["zéro", "zero;0"],
  ["s'appeler", "to be called"],
  ["avoir", "to have;have"],
  ["avoir ... ans;avoir...ans", "to be ... years old;to be...years old"],
  ["Son anniversaire c'est le", "His birthday is the;Her birthday is the"]
]);
