/* Y10U2.16 — 2.3 L5 · Describe a wedding. / Décris un mariage.
   Year 10 · Unité 2 — La famille et les amis — family, friends and relationships
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y10U2.16", [
  ["il est important de", "it is important to;it's important to"],
  ["important", "important"],
  ["différent", "different"],
  ["j'ai choisi d'étudier", "I chose to study"],
  ["il est important de + inf", "it is important to + inf"],
  ["tout", "all"],
  ["organiser", "to organise;to organize;organise"],
  ["donner son avis", "to give one's opinion"],
  ["le matin", "morning"],
  ["la nuit", "night"],
  ["tard", "late"],
  ["la sortie scolaire", "school trip"],
  ["le type", "type;kind;sort"],
  ["quand", "when"],
  ["extraordinaire", "extraordinary"],
  ["la sortie", "the exit;exit"],
  ["étonnant", "surprising;amazing"],
  ["nouveau;nouveaux;nouvelle", "new"],
  ["les données", "data"],
  ["souvent", "often"],
  ["association", "organisation;charity;club;association"],
  ["chez", "at the house of;to the house of"],
  ["spécial", "special"],
  ["presque", "nearly;almost"],
  ["le cadeau", "present;gift"],
  ["la chose", "thing"],
  ["la mémoire", "memory"],
  ["l'occasion", "occasion;chance;opportunity"],
  ["le souvenir", "souvenir;memory"],
  ["la surprise", "surprise"],
  ["avec", "with"],
  ["donner", "to give;give"],
  ["fêter", "to celebrate;party;to party;celebrate"],
  ["inviter", "to invite"],
  ["offrir", "to offer"],
  ["rappeler;se rappeler de", "to recall;remind;to remember"],
  ["recevoir", "to receive;receive"],
  ["se souvenir de", "to remember;remember"],
  ["sortir", "to go out;exit;leave;to leave;go out;to take out;to exit"],
  ["surprendre", "to surprise"],
  ["la même chose", "same thing"],
  ["anniversaire", "birthday"],
  ["la date", "the date;date"],
  ["Son anniversaire c'est le", "His birthday is the;Her birthday is the"],
  ["lien", "link"],
  ["mari", "husband"],
  ["mariage", "wedding;marriage"],
  ["promesse", "promise"],
  ["union", "union"],
  ["tous", "everyone;all of them"],
  ["tout le monde", "everybody;everyone"],
  ["promettre", "to promise"],
  ["réunir", "to gather;meet;reunite"],
  ["late", "tard"]
]);
