/* Y10U4.4 — L4 · Will you go to university? / Vas-tu aller / Iras-tu à l'université?
   Year 10 · Unité 4 — Le collège et l'avenir — school and future opportunities
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y10U4.4", [
  ["je pense que", "I think that"],
  ["je trouve que;je pense que", "I think that;i find that"],
  ["il faut que je fasse attention", "it is necessary that I be careful"],
  ["puisque", "since;because (higher level)"],
  ["à l'avenir;dans le futur", "in the future"],
  ["apprendre", "to learn;learn"],
  ["étudier", "to study;study"],
  ["je n'aime pas", "I don't like"],
  ["je préfère", "I prefer"],
  ["j'étudie", "I study;I am studying"],
  ["le meilleur", "best"],
  ["le pire;pire", "worst"],
  ["lire", "to read;read"],
  ["écrire", "to write"],
  ["travailler", "to work;work"],
  ["répondre", "to answer;to respond;to reply;respond"],
  ["poser", "to ask"],
  ["répéter", "to repeat;repeat"],
  ["utiliser", "to use;use"],
  ["écrire un texte", "to write a text"],
  ["poser une question", "to ask a question"],
  ["répondre à une question", "to answer a question"],
  ["travailler en groupe", "to work in a group"],
  ["faire attention", "to pay attention;pay attention"],
  ["noter", "to note"],
  ["se concentrer", "to concentrate;to focus"],
  ["se taire", "to be quiet"],
  ["expliquer", "to explain;explain"],
  ["enseigner", "to teach"],
  ["prêter", "to lend"],
  ["emprunter", "to borrow"],
  ["faire des progrès", "to make progress"],
  ["participer à une discussion", "to take part in a discussion"],
  ["expliquer une réponse", "to explain an answer"],
  ["la salle de classe", "classroom"],
  ["l'expérience", "experience"],
  ["Je n'aime pas l'uniforme", "I don't like the uniform"],
  ["silence", "silence"],
  ["en classe", "in class"],
  ["écrire un compte-rendu", "to write a report"],
  ["la classe", "class;classroom"],
  ["le cahier;cahier", "exercise book;notebook"],
  ["fait;fait de + nom", "does;did;made of + noun"],
  ["je n'aime pas le rock", "I don't like rock;I do not like rock"],
  ["Tu t'es fait mal", "You hurt yourself (s)"],
  ["Il s'est fait mal", "He hurt himself"],
  ["Elle s'est fait mal", "She hurt herself"],
  ["grâce à", "thanks to"],
  ["presque", "nearly;almost"],
  ["plutôt", "rather;instead"],
  ["surtout", "especially;above all"],
  ["travailleur", "hardworking (m)"],
  ["travailleuse", "hardworking (f)"],
  ["rather", "plutôt"],
  ["especially", "surtout"],
  ["ainsi", "so;thus"],
  ["également", "also;too;as well;equally"],
  ["cependant;pourtant;toutefois", "however"]
]);
