/* Y10U4.3 — L3 · (Higher Only) (Simple / Inflectional) Future Tense
   Year 10 · Unité 4 — Le collège et l'avenir — school and future opportunities
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y10U4.3", [
  ["c'est incroyable", "it's unbelievable;it's incredible"],
  ["il faut que je fasse attention", "it is necessary that I be careful"],
  ["puisque", "since;because (higher level)"],
  ["ce que j'aime c'est", "what I like it's;what I like it is"],
  ["apprendre", "to learn;learn"],
  ["langue", "language"],
  ["maths", "math"],
  ["science", "science"],
  ["théâtre", "theater"],
  ["étudier", "to study;study"],
  ["français", "French"],
  ["j'étudie", "I study;I am studying"],
  ["le meilleur", "best"],
  ["le pire;pire", "worst"],
  ["plus", "more"],
  ["moins", "less;minus"],
  ["lire", "to read;read"],
  ["écrire", "to write"],
  ["travailler", "to work;work"],
  ["répondre", "to answer;to respond;to reply;respond"],
  ["poser", "to ask"],
  ["répéter", "to repeat;repeat"],
  ["utiliser", "to use;use"],
  ["écrire un texte", "to write a text"],
  ["poser une question", "to ask a question"],
  ["répondre à une question", "to answer a question"],
  ["travailler en groupe", "to work in a group"],
  ["faire attention", "to pay attention;pay attention"],
  ["faire des progrès", "to make progress"],
  ["expliquer une réponse", "to explain an answer"],
  ["la salle de classe", "classroom"],
  ["l'expérience", "experience"],
  ["C'est interdit", "It's forbidden;it is forbidden"],
  ["silence", "silence"],
  ["en classe", "in class"],
  ["écrire un compte-rendu", "to write a report"],
  ["la classe", "class;classroom"],
  ["le cahier;cahier", "exercise book;notebook"],
  ["le stylo", "pen"],
  ["la science-fiction", "sci-fi"],
  ["fait;fait de + nom", "does;did;made of + noun"],
  ["Je n'aime pas la musique britannique car c'est ennuyeux", "I don't like British music because it's boring"],
  ["Mon genre de musique préférée c'est la pop", "my favourite genre of music is pop"],
  ["ça me fait rire", "it makes me laugh"],
  ["Tu t'es fait mal", "You hurt yourself (s)"],
  ["Il s'est fait mal", "He hurt himself"],
  ["Elle s'est fait mal", "She hurt herself"],
  ["Ils se sont fait mal", "They hurt themselves (mp)"],
  ["Elles se sont fait mal", "They hurt themselves (fp)"],
  ["malheureusement", "unfortunately;unluckily"],
  ["grâce à", "thanks to"],
  ["c'est-à-dire", "in other words"],
  ["travailleur", "hardworking (m)"],
  ["travailleuse", "hardworking (f)"],
  ["Ma meilleure amie est très prudente et aussi travailleuse que moi. On se connaît depuis 4 ans.", "My best friend is very careful and as hard-working as me. We have known each other for four years"],
  ["moins que", "less than;fewer than"],
  ["plus que", "more;-er than;than"],
  ["trop", "too much;too many"]
]);
