/* Y10U4.2 — L2 · What are your plans post-GCSE? Qu'est-ce que tu vas faire après les GCSEs ?
   Year 10 · Unité 4 — Le collège et l'avenir — school and future opportunities
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y10U4.2", [
  ["je pense que", "I think that"],
  ["je trouve que;je pense que", "I think that;i find that"],
  ["c'est génial", "it's great;it is great;It's awesome"],
  ["c'est incroyable", "it's unbelievable;it's incredible"],
  ["je n'y vais plus", "I'm not going there anymore"],
  ["puisque", "since;because (higher level)"],
  ["ce que j'aime c'est", "what I like it's;what I like it is"],
  ["difficile", "difficult;hard"],
  ["facile", "easy"],
  ["impossible", "impossible"],
  ["inutile", "useless;not useful"],
  ["simple", "simple"],
  ["utile", "useful;helpful"],
  ["langue", "language"],
  ["maths", "math"],
  ["science", "science"],
  ["théâtre", "theater"],
  ["français", "French"],
  ["musique", "music"],
  ["technologie", "technology"],
  ["je n'aime pas", "I don't like"],
  ["je préfère", "I prefer"],
  ["strict", "strict"],
  ["fort", "strong;loud"],
  ["faible", "weak;feeble"],
  ["plus", "more"],
  ["moins", "less;minus"],
  ["tout", "all"],
  ["réussir", "to succeed;to achieve;to pass"],
  ["passer un examen", "to take a test"],
  ["s'ennuyer", "to be bored;to get bored"],
  ["noter", "to note"],
  ["écouter le professeur", "to listen to the teacher"],
  ["moins le quart", "quarter to"],
  ["le professeur", "teacher"],
  ["le résultat", "result"],
  ["Je n'aime pas l'uniforme", "I don't like the uniform"],
  ["C'est interdit", "It's forbidden;it is forbidden"],
  ["la science-fiction", "sci-fi"],
  ["après", "after;afterwards"],
  ["la musique classique", "classical music"],
  ["Je n'aime pas la musique britannique car c'est ennuyeux", "I don't like British music because it's boring"],
  ["Mon genre de musique préférée c'est la pop", "my favourite genre of music is pop"],
  ["je n'aime pas le rock", "I don't like rock;I do not like rock"],
  ["la technologie", "technology;tech"],
  ["malheureusement", "unfortunately;unluckily"],
  ["grâce à", "thanks to"],
  ["c'est-à-dire", "in other words"],
  ["il est difficile de", "it is difficult to"],
  ["aussi", "also;as well;too"],
  ["aussi...que;aussi que", "as...as;as as"],
  ["also", "aussi"],
  ["as...as", "aussi...que"],
  ["moins que", "less than;fewer than"],
  ["plus que", "more;-er than;than"],
  ["sévère", "severe;strict;harsh"],
  ["trop", "too much;too many"],
  ["tout le monde", "everybody;everyone"]
]);
