/* Y11U5.2 — 5.1 L2 · Where do you like to spend your holidays and why?
   Year 11 · Unité 5 — Les voyages et le tourisme — travel, tourism and accommodation
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y11U5.2", [
  ["la côte", "coast"],
  ["l'endroit", "place"],
  ["la nature", "nature"],
  ["le paysage", "landscape"],
  ["la plage", "beach"],
  ["la province", "province"],
  ["la région", "region"],
  ["le sable", "sand"],
  ["la zone", "zone"],
  ["observer", "to observe;watch"],
  ["j'ai découvert", "I discovered;i have discovered"],
  ["j'ai dû", "I had to"],
  ["j'ai pu", "I was able to"],
  ["j'ai su", "I knew"],
  ["j'ai voulu", "I wanted"],
  ["la ville;une ville", "the town;a town;town;the city;a city;city"],
  ["j'attire", "I attract;I am attracting"],
  ["je découvre", "I discover;I am discovering"],
  ["inconnu", "unknown"],
  ["l'accent;un accent", "the accent;an accent;accent"],
  ["l'accès;un accès", "the access;an access;access"],
  ["le lendemain;un lendemain", "the next day;a next day;next day;the following day;a following day;following day"],
  ["le lieu;un lieu", "the place;a place;place"],
  ["le signe;un signe", "the sign;a sign;sign"],
  ["la sortie;une sortie", "the exit;an exit;exit;the way out;a way out;way out"],
  ["multiculturel", "multicultural"],
  ["permanent", "permanent"],
  ["vaste", "vast;huge"],
  ["historique", "historic;historical"],
  ["international", "international"],
  ["local", "local"],
  ["national", "national"],
  ["naturel", "natural"],
  ["principal", "main;principal"],
  ["le port;un port", "the port;a port;port;the harbour;a harbour;harbour"],
  ["parmi", "among;amongst"],
  ["j'observe", "I observe;I am observing;I watch;I am watching"],
  ["j'ai plaint", "I pitied;I have pitied"],
  ["je suis sortie", "I went out f;I have gone out f"],
  ["je surveille", "I supervise;I am supervising;I watch;I am watching"],
  ["nous surveillons", "we supervise;we are supervising;we watch;we are watching"],
  ["je signe", "I sign;I am signing"],
  ["il signe", "he signs;he is signing"],
  ["elle signe", "she signs;she is signing"],
  ["la ville est plus animée que", "the town is livelier than;the city is livelier than"],
  ["la ville me plait", "I like the town;I like the city"],
  ["dans ma région", "in my region;in my area"],
  ["dans ma ville", "in my town;in my city"],
  ["pour rendre ma ville meilleure", "to make my town better;to make my city better"],
  ["le problème principal", "the main problem"],
  ["au centre-ville", "in the town centre;in the city centre;in the center of town;downtown"],
  ["en ville", "in town;in the city"]
]);
