/* Y11U5.5 — 5.1 L5 · Past – Perfect with 'être'
   Year 11 · Unité 5 — Les voyages et le tourisme — travel, tourism and accommodation
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y11U5.5", [
  ["arrivée (f)", "arrival"],
  ["D'un côté;D'une part", "on the one hand"],
  ["d'un autre côté;d'autre part", "on the other hand"],
  ["partout", "everywhere"],
  ["montrer", "to show;show"],
  ["j'ai été", "I was;I have been"],
  ["j'ai eu", "I had;i've had"],
  ["j'ai mis", "I put;i have put"],
  ["j'ai vu", "I saw;i have watched"],
  ["j'ai fait", "I did;i have done"],
  ["arriver", "to arrive;to manage"],
  ["partir", "to leave;to depart;leave;depart"],
  ["rentrer", "to go back in;return"],
  ["retourner", "to return;come back"],
  ["revenir", "to come back;return;to return;come back"],
  ["l'arrivée", "the arrival;arrival"],
  ["je montre", "I show;I am showing"],
  ["j'ai pris", "I took;I have taken"],
  ["j'ai reconnu", "I recognised;I have recognised;I recognized;I have recognized"],
  ["j'ai traduit", "I translated;I have translated"],
  ["je suis allé", "I went;I have gone"],
  ["je suis arrivé", "I arrived;I have arrived"],
  ["je suis monté", "I went up;I have gone up;I climbed;I have climbed"],
  ["je suis parti", "I left;I have left"],
  ["je suis rentré", "I returned;I have returned;I came back;I have come back"],
  ["je suis retourné", "I returned;I have returned;I went back;I have gone back"],
  ["je suis revenu", "I came back;I have come back"],
  ["je suis sorti", "I went out;I have gone out"],
  ["le tour;un tour", "the tour;a tour;tour;the turn;a turn;turn"],
  ["la tour;une tour", "the tower;a tower;tower"],
  ["la tour Eiffel", "the Eiffel Tower;Eiffel Tower"],
  ["haut", "high;tall"],
  ["le 14 juillet", "the 14th of July;Bastille Day"],
  ["je suis allée", "I went f;I have gone f"],
  ["je suis arrivée", "I arrived f;I have arrived f"],
  ["je suis montée", "I went up f;I have gone up f;I climbed f;I have climbed f"],
  ["je suis partie", "I left f;I have left f"],
  ["je suis rentrée", "I returned f;I have returned f;I came back f;I have come back f"],
  ["je suis retournée", "I returned f;I have returned f;I went back f;I have gone back f"],
  ["je suis revenue", "I came back f;I have come back f"],
  ["je suis sortie", "I went out f;I have gone out f"],
  ["j'arrive", "I arrive;I am arriving"],
  ["il arrive", "he arrives;he is arriving"],
  ["elle arrive", "she arrives;she is arriving"],
  ["nous arrivons", "we arrive;we are arriving"],
  ["il part", "he leaves;he is leaving"],
  ["elle part", "she leaves;she is leaving"],
  ["je retourne", "I return;I am returning;I go back;I am going back"],
  ["il retourne", "he returns;he is returning;he goes back;he is going back"],
  ["elle retourne", "she returns;she is returning;she goes back;she is going back"],
  ["je monte", "I go up;I am going up;I climb;I am climbing"],
  ["nous montons", "we go up;we are going up;we climb;we are climbing"],
  ["je rentre", "I return;I am returning;I go back;I am going back;I come back;I am coming back"],
  ["nous rentrons", "we return;we are returning;we go back;we are going back;we come back;we are coming back"],
  ["nous revenons", "we come back;we are coming back"],
  ["la montagne;une montagne", "the mountain;a mountain;mountain"],
  ["partout dans le monde", "everywhere in the world;all over the world"]
]);
