/* Y11U5.1 — 5.1 L1 · Would you like to visit a French-speaking country?
   Year 11 · Unité 5 — Les voyages et le tourisme — travel, tourism and accommodation
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y11U5.1", [
  ["entre", "between;in between"],
  ["la côte", "coast"],
  ["l'endroit", "place"],
  ["la plage", "beach"],
  ["fermer", "to close;shut (down)"],
  ["montrer", "to show;show"],
  ["l'Afrique;une Afrique", "Africa"],
  ["l'Algérie;une Algérie", "Algeria"],
  ["l'Amérique;une Amérique", "America"],
  ["l'Asie;une Asie", "Asia"],
  ["le Canada;un Canada", "Canada"],
  ["la capitale;une capitale", "the capital;a capital;capital"],
  ["l'Europe;une Europe", "Europe"],
  ["la France;une France", "France"],
  ["Madagascar", "Madagascar"],
  ["la Martinique;une Martinique", "Martinique"],
  ["Paris", "Paris"],
  ["en Angleterre", "in England"],
  ["la France d'Outre-mer;une France d'Outre-mer", "Overseas France"],
  ["la ville;une ville", "the town;a town;town;the city;a city;city"],
  ["encore", "again;still;yet"],
  ["la boulangerie;une boulangerie", "the bakery;a bakery;bakery"],
  ["le château;un château", "the castle;a castle;castle;the palace;a palace;palace"],
  ["le marché;un marché", "the market;a market;market"],
  ["le musée;un musée", "the museum;a museum;museum"],
  ["le pont;un pont", "the bridge;a bridge;bridge"],
  ["le tableau;un tableau", "the painting;a painting;painting;the picture;a picture;picture"],
  ["je visite", "I visit;I am visiting"],
  ["j'entre", "I enter;I am entering;I go in;I am going in"],
  ["je ferme", "I close;I am closing;I shut;I am shutting"],
  ["je montre", "I show;I am showing"],
  ["j'attire", "I attract;I am attracting"],
  ["je découvre", "I discover;I am discovering"],
  ["francophone", "French-speaking;French speaking"],
  ["fermé", "closed;shut"],
  ["on peut visiter", "one can visit;we can visit;you can visit"],
  ["il faut visiter", "one must visit;we must visit;you must visit"],
  ["j'ai visité", "I visited;I have visited"],
  ["la ferme;une ferme", "the farm;a farm;farm"],
  ["la ville est plus animée que", "the town is livelier than;the city is livelier than"],
  ["la ville me plait", "I like the town;I like the city"],
  ["dans ma ville", "in my town;in my city"],
  ["ferme le robinet", "turn off the tap"],
  ["je vais fermer", "I am going to close;I am going to shut"],
  ["je fermerai", "I will close;I will shut"],
  ["pour rendre ma ville meilleure", "to make my town better;to make my city better"],
  ["au centre-ville", "in the town centre;in the city centre;in the center of town;downtown"],
  ["en ville", "in town;in the city"]
]);
