/* Y11U5.9 — 5.2 L3 · Role Play – at the hotel / campsite (reservations, information)
   Year 11 · Unité 5 — Les voyages et le tourisme — travel, tourism and accommodation
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y11U5.9", [
  ["disponible", "available;free"],
  ["inclus", "included"],
  ["libre", "free;available"],
  ["plein", "full"],
  ["supplémentaire", "extra"],
  ["arrivée (f)", "arrival"],
  ["départ (m)", "departure"],
  ["passeport (m)", "passport"],
  ["renseignement (m)", "piece of information"],
  ["accueillir", "to welcome;welcome"],
  ["chercher", "to look for;to search;to search for;to look"],
  ["demander à quelqu'un de", "to ask someone to"],
  ["se demander", "to wonder;to ask oneself;wonder;to ask yourself"],
  ["remercier", "to thank"],
  ["remplir", "to fill in;to fill"],
  ["signer", "to sign"],
  ["vérifier", "to check;to verify"],
  ["l'arrivée", "the arrival;arrival"],
  ["un renseignement", "a piece of information"],
  ["le signe;un signe", "the sign;a sign;sign"],
  ["je suis arrivée", "I arrived f;I have arrived f"],
  ["je signe", "I sign;I am signing"],
  ["il signe", "he signs;he is signing"],
  ["elle signe", "she signs;she is signing"],
  ["nous signons", "we sign;we are signing"],
  ["je vérifie", "I check;I am checking;I verify;I am verifying"],
  ["il vérifie", "he checks;he is checking;he verifies;he is verifying"],
  ["elle vérifie", "she checks;she is checking;she verifies;she is verifying"],
  ["nous vérifions", "we check;we are checking;we verify;we are verifying"],
  ["le renseignement;un renseignement", "the information;an information;information;the piece of information;a piece of information;piece of information"],
  ["je cherche", "I look for;I am looking for;I search;I am searching"],
  ["il cherche", "he looks for;he is looking for;he searches;he is searching"],
  ["elle cherche", "she looks for;she is looking for;she searches;she is searching"],
  ["nous cherchons", "we look for;we are looking for;we search;we are searching"],
  ["je demande", "I ask;I am asking;I ask for;I am asking for"],
  ["il demande", "he asks;he is asking;he asks for;he is asking for"],
  ["elle demande", "she asks;she is asking;she asks for;she is asking for"],
  ["nous demandons", "we ask;we are asking;we ask for;we are asking for"],
  ["je me demande", "I wonder;I am wondering"],
  ["il se demande", "he wonders;he is wondering"],
  ["elle se demande", "she wonders;she is wondering"],
  ["nous nous demandons", "we wonder;we are wondering"],
  ["j'accueille", "I welcome;I am welcoming"],
  ["nous accueillons", "we welcome;we are welcoming"],
  ["je remercie", "I thank;I am thanking"],
  ["nous remercions", "we thank;we are thanking"],
  ["je remplis", "I fill;I am filling;I fill in;I am filling in"],
  ["nous remplissons", "we fill;we are filling;we fill in;we are filling in"],
  ["cela signifie", "it means"],
  ["je signifie", "I mean;I am meaning;I signify;I am signifying"]
]);
