/* Y11U5.4 — 5.1 L4 · Past – Perfect with 'avoir'
   Year 11 · Unité 5 — Les voyages et le tourisme — travel, tourism and accommodation
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y11U5.4", [
  ["en fait", "in fact"],
  ["j'ai découvert", "I discovered;i have discovered"],
  ["j'ai été", "I was;I have been"],
  ["j'ai eu", "I had;i've had"],
  ["j'ai mis", "I put;i have put"],
  ["je me suis plaint", "I complained"],
  ["j'ai voulu", "I wanted"],
  ["j'ai vu", "I saw;i have watched"],
  ["j'ai fait", "I did;i have done"],
  ["j'ai plaint", "I pitied;I have pitied"],
  ["j'ai pris", "I took;I have taken"],
  ["j'ai reconnu", "I recognised;I have recognised;I recognized;I have recognized"],
  ["j'ai traduit", "I translated;I have translated"],
  ["je suis allé", "I went;I have gone"],
  ["je suis arrivé", "I arrived;I have arrived"],
  ["je suis monté", "I went up;I have gone up;I climbed;I have climbed"],
  ["je suis parti", "I left;I have left"],
  ["je suis rentré", "I returned;I have returned;I came back;I have come back"],
  ["je suis retourné", "I returned;I have returned;I went back;I have gone back"],
  ["je suis revenu", "I came back;I have come back"],
  ["je suis sorti", "I went out;I have gone out"],
  ["le tour;un tour", "the tour;a tour;tour;the turn;a turn;turn"],
  ["la tour;une tour", "the tower;a tower;tower"],
  ["la tour Eiffel", "the Eiffel Tower;Eiffel Tower"],
  ["haut", "high;tall"],
  ["le 14 juillet", "the 14th of July;Bastille Day"],
  ["je suis allée", "I went f;I have gone f"],
  ["je suis arrivée", "I arrived f;I have arrived f"],
  ["je suis montée", "I went up f;I have gone up f;I climbed f;I have climbed f"],
  ["je suis partie", "I left f;I have left f"],
  ["je suis rentrée", "I returned f;I have returned f;I came back f;I have come back f"],
  ["je suis retournée", "I returned f;I have returned f;I went back f;I have gone back f"],
  ["je suis revenue", "I came back f;I have come back f"],
  ["je suis sortie", "I went out f;I have gone out f"],
  ["il se plaint", "he complains;he is complaining"],
  ["elle se plaint", "she complains;she is complaining"],
  ["il fait beau", "it is fine;it is nice;the weather is fine;the weather is nice"],
  ["il fait chaud", "it is hot;it is warm"],
  ["il fait froid", "it is cold"],
  ["il fait mauvais", "the weather is bad;it is bad weather"],
  ["quand il fait beau", "when it is fine;when it is nice;when the weather is fine"],
  ["s'il fait beau", "if it is fine;if it is nice;if the weather is fine"],
  ["nous avons fait", "we did;we have done;we made;we have made"]
]);
