/* Y11U6.7 — L9 · Role Play – directions in town
   Year 11 · Unité 6 — Ma ville et l'environnement — transport, shopping, town and the environment
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y11U6.7", [
  ["gauche (f)", "left"],
  ["ailleurs", "somewhere else;besides"],
  ["loin (de)", "far (from)"],
  ["proche", "near"],
  ["à côté de", "next to;beside"],
  ["distance (f)", "distance"],
  ["droite (f)", "right"],
  ["face (f)", "front;face;side"],
  ["mètre (m)", "metre"],
  ["route (f)", "road;way;route"],
  ["derrière", "behind;at the back"],
  ["devant", "in front of"],
  ["entre", "between;in between"],
  ["envers", "towards"],
  ["près de", "near;close by;nearby"],
  ["vers", "towards"],
  ["suivi", "followed"],
  ["rechercher", "to look for;to search"],
  ["suivre", "to follow;follow"],
  ["tourner", "to turn;turn"],
  ["traverser", "to cross;cross"],
  ["Allez à gauche", "Go left"],
  ["tournez à droite", "turn right;turn to the right"],
  ["tournez à gauche", "turn left"],
  ["Traversez la rue", "Cross the street;cross the street;cross the road"],
  ["C'est à côté de la gare", "It is next to the station;it is close to the station"],
  ["Allez à droite", "go right"],
  ["j'entre", "I enter;I am entering;I go in;I am going in"],
  ["la distance;une distance", "the distance;a distance;distance"],
  ["le mètre;un mètre", "the metre;a metre;metre;the meter;a meter;meter"],
  ["la route;une route", "the road;a road;road;the route;a route;route"],
  ["je tourne", "I turn;I am turning"],
  ["il tourne", "he turns;he is turning"],
  ["tournez", "turn"],
  ["elle tourne", "she turns;she is turning"],
  ["je traverse", "I cross;I am crossing"],
  ["il traverse", "he crosses;he is crossing"],
  ["elle traverse", "she crosses;she is crossing"],
  ["traversez", "cross"],
  ["suivez", "follow"],
  ["la droite;à droite", "the right;right"],
  ["en face de", "opposite;facing"],
  ["la gauche;à gauche", "the left;a left;left"],
  ["loin de", "far from"],
  ["je recherche", "I look for;I am looking for;I search for;I am searching for"]
]);
