/* Y8U4.3 — L4 · Sports and Hobbies - What other hobbies do you do?
   Year 8 · Unité 4 — Le temps libre — free time
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y8U4.3", [
  ["le sport", "sport;pe"],
  ["le tennis", "tennis"],
  ["la carte", "card"],
  ["les cartes", "cards"],
  ["l'instrument", "instrument"],
  ["l'équipe", "team"],
  ["je joue", "I play"],
  ["tu joues", "you play"],
  ["nous jouons", "we play"],
  ["je chante", "I sing"],
  ["tu chantes", "you sing"],
  ["nous chantons", "we sing"],
  ["je danse", "I dance"],
  ["tu danses", "you dance"],
  ["nous dansons", "we dance"],
  ["je pratique", "I practise"],
  ["tu pratiques", "you practise"],
  ["nous pratiquons", "we practise"],
  ["le vélo", "bike;cycling"],
  ["l'art", "art"],
  ["la danse", "dance;dancing"],
  ["la natation", "swimming"],
  ["je fais", "I do;I make"],
  ["tu fais", "you do;you make"],
  ["nous faisons", "we do;we make"],
  ["je fais partie de", "I am part of;I am a member of"],
  ["tu fais partie de", "you are part of;you are a member of"],
  ["nous faisons partie de", "we are part of;we are members of"],
  ["je fais une sortie", "I go on an outing"],
  ["tu fais une sortie", "you go on an outing"],
  ["nous faisons une sortie", "we go on an outing"],
  ["je fais les courses", "I do the shopping;I do the groceries;i do shopping"],
  ["tu fais les courses", "you do the shopping"],
  ["nous faisons les courses", "we do the shopping"],
  ["je cours", "I run"],
  ["tu cours", "you run"],
  ["je lis", "I read"],
  ["tu lis", "you read"],
  ["je reste", "I stay"],
  ["tu restes", "you stay"],
  ["je sors", "I go out"],
  ["tu sors", "you go out"],
  ["j'utilise", "I use"],
  ["tu utilises", "you use"],
  ["je vois", "I see"],
  ["tu vois", "you see"]
]);
