/* Y8U4.1 — L1 · Role Models — Describe a person important to you
   Year 8 · Unité 4 — Le temps libre — free time
   One pair per line: ["French", "English"]. Separate interchangeable
   forms with a semicolon — "le garçon;un garçon" / "the boy;a boy;boy".
   Add, remove or reorder freely: a word keeps its place in a student's
   progress as long as its French stays the same. */
BBA.list("Y8U4.1", [
  ["le modèle", "role model"],
  ["son", "his;her"],
  ["sa", "his;her;his her"],
  ["ses", "his;her"],
  ["je", "I"],
  ["tu", "you"],
  ["il", "he"],
  ["elle", "she"],
  ["nous", "we"],
  ["vous", "you"],
  ["ils", "they"],
  ["elles", "they"],
  ["j'aime", "I like;I love"],
  ["tu aimes", "you like;you love"],
  ["nous aimons", "we like;we love"],
  ["j'adore", "I adore;I love"],
  ["tu adores", "you adore;you love"],
  ["nous adorons", "we adore;we love"],
  ["je déteste", "I hate"],
  ["tu détestes", "you hate"],
  ["nous détestons", "we hate"],
  ["je prépare le dîner", "I prepare dinner;i make dinner"],
  ["tu prépares le dîner", "you prepare dinner"],
  ["nous préparons le dîner", "we prepare dinner"],
  ["je joue avec", "I play with"],
  ["tu joues avec", "you play with"],
  ["nous jouons avec", "we play with"],
  ["je regarde la télé", "I watch TV;I watch television;i watch the tv"],
  ["tu regardes la télé", "you watch TV;you watch television"],
  ["nous regardons la télé", "we watch TV;we watch television"],
  ["je vais", "I go;I am going;i'm going"],
  ["tu vas", "you go"],
  ["nous allons", "we go;we are going"],
  ["au café", "to the café;to the cafe"],
  ["à la piscine", "to the swimming pool;to the pool"],
  ["au centre commercial", "to the shopping centre;to the mall"],
  ["au fastfood", "to the fast food restaurant"],
  ["au magasin", "to the shop"],
  ["au marché", "to the market"],
  ["au parc", "to the park"],
  ["au stade", "to the stadium"],
  ["au théâtre", "to the theatre"],
  ["le café", "café;cafe"],
  ["le centre commercial", "shopping centre;shopping mall;mall"],
  ["le fastfood", "fast food restaurant"],
  ["le magasin", "shop;store"],
  ["le marché", "market"],
  ["le parc", "park"],
  ["la piscine", "swimming pool;pool"],
  ["le stade", "stadium"],
  ["le théâtre", "theatre"],
  ["car c'est", "because it is"]
]);
